### ISSUE TITLE
Not meant to duplicate .workshop/scripts from separate repo.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift-labs/lab-openshift-pipelines-with-tekton#20]
The `.workshop/scripts` should be a git submodule linked to `workshop-scripts` repo. Have somehow managed to create it as a copy and not as git submodule, even though `.gitmodule` exists. So created the wrong way. Will do PR to fix.

**Comment by danielhelfand** [comment]
Addressed by #24
